           
 
 <?php
 

 
 ?>
 
 <div id="setVideoInnerPlaylist" style="height: 0px;
           width: 100%;
           overflow: visible;
           position: relative;
           top: bottom;
           top: 100px;" >
 
           <div id="setVideoInnerPlaylistLayer" style="height: 50px; opacity: 0;
           width: 100%;
           background-color: rgba(0, 0, 0, 0.39); " >
                      
                <a style="  ;" href="javascript:void(0)"><img style=" height:100%;" src="<?=$protocol?><?php LOADDOMAINNAME?>/assets/images/ks-poster.png" alt="Nambia Timelapse 1"></a>

                <a style=" ;" href="javascript:void(0)"><img style=" height:100%;" src="<?=$protocol?><?php LOADDOMAINNAME?>/images/video-poster.png" alt="Nambia Timelapse 2"></a>

                <a style="  ;" href="javascript:void(0)"><img style=" height:100%;" src="<?=$protocol?><?php LOADDOMAINNAME?>/images/Incredibles_Teaser_640x272.png" alt="Nambia Timelapse 3"></a>
          
           </div>           
 </div>           
 
 <figure id="video_player" style="    margin-left: 0px;    margin-right: 0px;">
           
           
            <video id="video1" width="100%" poster="<?=$protocol?><?php LOADDOMAINNAME?>/assets/images/ks-poster.png"
                   
                   loop
                   muted
                   paused
                   controls
                
    
                   
                   >
                <source src="<?=$protocol?><?php LOADDOMAINNAME?>/assets/videos/<?php echo $videoSource;?>" type='video/mp4'>
                <p>Your user agent does not support the HTML5 Video element.</p>
                
<!--                hello -->
                
            </video>

           

        </figure>
      