  <!-- Start of the JSSOR Gallery -->
    <div>
        <h2 class="title">gallery</h2>

        <div id="slider1_container" style="width: 300px; height: 300px; overflow: hidden; ">
            <div u="loading" style=" top: 0px; left: 0px;">
                <div>
                {+filter: alpha(opacity=70); opacity:0.7;} style="position: ; display: block; background-color:
                #000; top: 0px; left: 0px;width: 100%;height:100%;">
            </div>
            <div style="position: ; display: block; background: url(<?=$protocol?><?php LOADDOMAINNAME?>/images/loading.gif) no-repeat center center;
=======
            <div style="position: ; display: block; background: url(<?=$protocol?><?php LOADDOMAINNAME?>/images/loading.gif) no-repeat center center;
top: 0px; left: 0px;width: 100%;height:100%;">
            </div> 
        </div>
        <div u="slides" style="cursor: move; position: ; left: 0px; top: 0px; width: 300px; height: 300px; overflow: hidden;">
            <div>
                <a u=image href="#">
	                <img src="<?=$protocol?><?php LOADDOMAINNAME?>/images/gallery/Air-Raid_Black_3-4_S7ARFW-343.png"/>
                </a>
                <div u=caption t="*" class="captionGrey">slideshow transition twins</div>
            </div>
            <div>
                <a u=image href="#">
	                <img src="<?=$protocol?><?php LOADDOMAINNAME?>/images/gallery/Air-Raid_Black_Back_S7ARFW-343.png"/>
                </a>
                <div u=caption t="*" class="captionGrey">random caption transition</div>
            </div>
            <div>
                <a u=image href="#">
	                <img src="<?=$protocol?><?php LOADDOMAINNAME?>/images/gallery/Air-Raid_Black_Front_S7ARFW-343.png"/>
                </a>
                <div u=caption t="*" class="captionGrey">mobile ready, touch swipe</div>
            </div>
            <div>
                <a u=image href="#">
	                <img src="<?=$protocol?><?php LOADDOMAINNAME?>/images/gallery/Air-Raid_Black_L-Side_S7ARFW-343.png"/>
                </a>
                <div u=caption t="*" class="captionGrey">responsive, scale smoothly</div>
            </div>
            <div>
                <a u=image href="#">
	                <img src="<?=$protocol?><?php LOADDOMAINNAME?>/images/gallery/Air-Raid_Black_R-Side_S7ARFW-343.png"/>
                </a>
                <div u=caption t="*" class="captionGrey">responsive, scale smoothly</div>
            </div>
        </div>
        <div u="navigator" class="jssorb01" style="position: absolute; bottom: 16px; right: 10px;">
            <div u="prototype" style="POSITION: absolute; WIDTH: 12px; HEIGHT: 12px;"></div>
        </div>
<span u="arrowleft" class="jssora05l">
</span>
<span u="arrowright" class="jssora05r">
</span>
        <a style="display: none" href="http://www.jssor.com">responsive jquery slider</a>
        <script>jssor_slider1_starter('slider1_container');</script>
    </div>
</div>
    <!-- EOF of the JSSOR Gallery -->