<!-- HTML5 Video Player with Playlist  -->


    <figure id="video_player">

        <video videoIndex="0" width="90%" height="auto" id="video1" poster="<?=$protocol?><?= $loaddomainname ?>/assets/images/<?=$assetVideoSet["poster"][0]?>"

               muted
               paused
               controls
            >

            <source src="<?=$protocol?><?= $loaddomainname ?>/assets/videos/<?= $assetVideoSet["video"][0];?>" type='video/mp4'>
            <p>Your user agent does not support the HTML5 Video element.</p>


        </video>

<!-- *****************************  Video End Event  *********************************** -->

<!--        <script>-->
<!--            -->
<!---->
<!--            video.onended = function(e) {-->
<!--                /*Do things here!*/-->
<!--            };-->
<!--        </script>-->

<!-- ***************************** EOF - Video End Event  *********************************** -->

        <figcaption>

        <div id="setVideoInnerPlaylistLayer1">
            <script>
                var video = document.getElementsByTagName('video')[0];

            </script>
                <?php

                foreach($assetVideoSet["video"] as $assetVideoSetKeys => $assetVideoSetValues) : ?>

            <div class="VideoPlaylist" id="VideoPlaylist">

                    <img index="<?php echo $assetVideoSetKeys?>" class="videoChange" key="<?=$assetVideoSetKeys?>" path="<?= $loaddomainname ?>"
                         filename="<?=$assetVideoSet["video"][$assetVideoSetKeys];?>"
                         src="<?=$protocol?><?= $loaddomainname ?>/assets/images/<?=$assetVideoSet["poster"][$assetVideoSetKeys];?>"
                         alt="<?=$assetVideoSet["poster"][$assetVideoSetKeys];?>">

            </div>



                <?php endforeach; ?>
    </div>

        </figcaption>

<!---->
<!--<div id="setVideoInnerPlaylist1" >-->
<!---->
<!--</div>-->

</figure>


<script>


    video.addEventListener('ended', function(e) {

        console.log("just ended :"+$("#video1").attr("videoIndex"));
        console.log("all :"+$(".VideoPlaylist").length);

        var outofit =  $("#video1").attr("videoIndex")/1+1+1;

        if (outofit>$(".VideoPlaylist").length){

            var nextIndex =  0;
            console.log("next index :"+ nextIndex );
            console.log("next :"+$(".videoChange[index="+nextIndex+"]").attr("filename"));
            video.src = "<?=$protocol?>"+$(".videoChange[index="+nextIndex+"]").attr("path")+"/assets/videos/"+$(".videoChange[index="+nextIndex+"]").attr("filename");
            console.log(video.src);
            $("#video1").attr("videoIndex",nextIndex);
            video.play();

        }else
        {

            var nextIndex =  $("#video1").attr("videoIndex")/1+1;
            console.log("next index :"+ nextIndex );
            console.log("next :"+$(".videoChange[index="+nextIndex+"]").attr("filename"));
            video.src = "<?=$protocol?>"+$(".videoChange[index="+nextIndex+"]").attr("path")+"/assets/videos/"+$(".videoChange[index="+nextIndex+"]").attr("filename");
            console.log(video.src);
            $("#video1").attr("videoIndex",nextIndex);
            video.play();

        }

    }, false);

</script>
<!-- EOF - HTML5 Video Player with Playlist  -->


